(rule
  (target pg_cflags.txt)
  (action (with-stdout-to %{target}
            (bash "printf -- \"-I%s\" \"$(pg_config --includedir-server)\""))))

(rule
  (target plocaml_config.ml)
  (action (with-stdout-to %{target}
            (bash "printf \"let stdlib_path = \\\"%s\\\"\\n\" \"$(ocamlc -where)\""))))

(library
  (name plocaml_stubs)
  (modules)
  (foreign_stubs
    (language c)
    (names stub plocaml_spi)
    (flags (:include pg_cflags.txt) -fPIC -D_GNU_SOURCE -std=c23)
    (extra_deps bootstrap.ml plocaml.h)))

(executable
  (name runtime)
  (modules runtime plocaml_config bootstrap)
  (libraries compiler-libs.toplevel plocaml_stubs)
  (modes (byte shared_object)))
