-- Ported from PostgreSQL src/pl/plpython/sql/plpython_error.sql (REL_16_STABLE).
-- Python-only pieces omitted: typed plpy.spiexceptions classes and custom
-- exception.sqlstate. Tracebacks are reported in CONTEXT like PL/Python.

/* Flat out syntax error
 */
CREATE FUNCTION ocaml_syntax_error() RETURNS text
        AS $$
  let x =
$$ LANGUAGE plocamlu;

/* With check_function_bodies = false the function should get defined
 * and the error reported when called.
 */
SET check_function_bodies = false;

CREATE OR REPLACE FUNCTION ocaml_syntax_error() RETURNS text
        AS $$
  let x =
$$ LANGUAGE plocamlu;

SELECT ocaml_syntax_error();
/* Run the function twice to check if the hashtable entry gets cleaned up */
SELECT ocaml_syntax_error();

RESET check_function_bodies;

/* Flat out syntax error
 */
CREATE FUNCTION sql_syntax_error() RETURNS text
        AS $$
  ignore (PL.execute "syntax error")
$$ LANGUAGE plocamlu;

SELECT sql_syntax_error();


/* check the handling of uncaught ocaml exceptions
 */
CREATE FUNCTION exception_index_invalid(text) RETURNS text
	AS $$
  args.(1)
$$ LANGUAGE plocamlu;

SELECT exception_index_invalid('test');


/* check handling of nested exceptions
 */
CREATE FUNCTION exception_index_invalid_nested() RETURNS text
	AS $$
let rv = PL.execute "SELECT test5('foo')" in
(match rv.rows.(0) with (_, v) :: _ -> v | [] -> PL.Null)
$$ LANGUAGE plocamlu;

SELECT exception_index_invalid_nested();


/* a typo
 */
CREATE FUNCTION invalid_type_uncaught(a text) RETURNS text
	AS $$
if not (Hashtbl.mem sd "plan") then
  PL.set sd "plan" (PL.prepare "SELECT fname FROM users WHERE lname = $1" [|"test"|]);
let rv = PL.execute_plan (PL.get sd "plan") [| a |] in
if Array.length rv.rows > 0 then List.assoc "fname" rv.rows.(0)
else PL.Null
$$ LANGUAGE plocamlu;

SELECT invalid_type_uncaught('rick');


/* for what it's worth catch the exception generated by
 * the typo, and return None
 */
CREATE FUNCTION invalid_type_caught(a text) RETURNS text
	AS $$
if not (Hashtbl.mem sd "plan") then
  (try
    PL.set sd "plan" (PL.prepare "SELECT fname FROM users WHERE lname = $1" [|"test"|])
  with Failure ex ->
    PL.notice ex);
if not (Hashtbl.mem sd "plan") then PL.Null
else
  let rv = PL.execute_plan (PL.get sd "plan") [| a |] in
  if Array.length rv.rows > 0 then List.assoc "fname" rv.rows.(0)
  else PL.Null
$$ LANGUAGE plocamlu;

SELECT invalid_type_caught('rick');


/* for what it's worth catch the exception generated by
 * the typo, and reraise it as a plain error
 */
CREATE FUNCTION invalid_type_reraised(a text) RETURNS text
	AS $$
if not (Hashtbl.mem sd "plan") then
  (try
    PL.set sd "plan" (PL.prepare "SELECT fname FROM users WHERE lname = $1" [|"test"|])
  with Failure ex ->
    PL.error ex);
let rv = PL.execute_plan (PL.get sd "plan") [| a |] in
if Array.length rv.rows > 0 then List.assoc "fname" rv.rows.(0)
else PL.Null
$$ LANGUAGE plocamlu;

SELECT invalid_type_reraised('rick');


/* no typo no messing about
 */
CREATE FUNCTION valid_type(a text) RETURNS text
	AS $$
if not (Hashtbl.mem sd "plan") then
  PL.set sd "plan" (PL.prepare "SELECT fname FROM users WHERE lname = $1" [|"text"|]);
let rv = PL.execute_plan (PL.get sd "plan") [| a |] in
if Array.length rv.rows > 0 then List.assoc "fname" rv.rows.(0)
else PL.Null
$$ LANGUAGE plocamlu;

SELECT valid_type('rick');

/* error in nested functions to get a traceback
*/
CREATE FUNCTION nested_error() RETURNS text
	AS $$
let rec fun1 () = PL.error "boom"; ()
and fun2 () = fun1 (); ()
and fun3 () = fun2 (); ()
in
fun3 ();
PL.String "not reached"
$$ LANGUAGE plocamlu;

SELECT nested_error();

/* raising Failure is just like calling PL.error
*/
CREATE FUNCTION nested_error_raise() RETURNS text
	AS $$
let rec fun1 () = failwith "boom"; ()
and fun2 () = fun1 (); ()
and fun3 () = fun2 (); ()
in
fun3 ();
PL.String "not reached"
$$ LANGUAGE plocamlu;

SELECT nested_error_raise();

/* using PL.warning should not produce a traceback
*/
CREATE FUNCTION nested_warning() RETURNS text
	AS $$
let rec fun1 () = PL.warning "boom"
and fun2 () = fun1 ()
and fun3 () = fun2 ()
in
fun3 ();
PL.String "you've been warned"
$$ LANGUAGE plocamlu;

SELECT nested_warning();

/* AttributeError at toplevel used to give segfaults with the traceback
*/
CREATE FUNCTION toplevel_attribute_error() RETURNS void AS
$$
ignore PL.nonexistent
$$ LANGUAGE plocamlu;

SELECT toplevel_attribute_error();

/* Calling PL/OCaml functions from SQL and vice versa should not lose context.
 */
CREATE OR REPLACE FUNCTION ocaml_traceback() RETURNS void AS $$
let rec first () = second (); ()
and second () = third (); ()
and third () = ignore (PL.execute "select sql_error()")
in
first ();
()
$$ LANGUAGE plocamlu;

CREATE OR REPLACE FUNCTION sql_error() RETURNS void AS $$
begin
  select 1/0;
end
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION ocaml_from_sql_error() RETURNS void AS $$
begin
  select ocaml_traceback();
end
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION sql_from_ocaml_error() RETURNS void AS $$
ignore (PL.execute "select sql_error()");
()
$$ LANGUAGE plocamlu;

SELECT ocaml_traceback();
SELECT sql_error();
SELECT ocaml_from_sql_error();
SELECT sql_from_ocaml_error();

/* check catching specific types of exceptions
 */
CREATE TABLE specific (
    i integer PRIMARY KEY
);

CREATE FUNCTION specific_exception(i integer) RETURNS void AS
$$
try
  let i_sql = match i with
    | PL.Null -> "NULL"
    | PL.Int n -> string_of_int n
    | _ -> "NULL"
  in
  ignore (PL.execute (Printf.sprintf "insert into specific values (%s)" i_sql));
  ()
with Failure ex ->
  if String.contains ex 'n' || true then
    PL.notice ("SPI error: " ^ ex);
  ()
$$ LANGUAGE plocamlu;

SELECT specific_exception(2);
SELECT specific_exception(NULL);
SELECT specific_exception(2);

/* SPI errors in PL/OCaml functions should preserve the SQLSTATE value
 */
CREATE FUNCTION ocaml_unique_violation() RETURNS void AS $$
ignore (PL.execute "insert into specific values (1)");
ignore (PL.execute "insert into specific values (1)");
()
$$ LANGUAGE plocamlu;

CREATE FUNCTION catch_ocaml_unique_violation() RETURNS text AS $$
begin
    begin
        perform ocaml_unique_violation();
    exception when unique_violation then
        return 'ok';
    end;
    return 'not reached';
end;
$$ language plpgsql;

SELECT catch_ocaml_unique_violation();

/* manually starting subtransactions - a bad idea
 */
CREATE FUNCTION manual_subxact() RETURNS void AS $$
ignore (PL.execute "savepoint save");
ignore (PL.execute "create table foo(x integer)");
ignore (PL.execute "rollback to save");
()
$$ LANGUAGE plocamlu;

SELECT manual_subxact();

/* same for prepared plans
 */
CREATE FUNCTION manual_subxact_prepared() RETURNS void AS $$
let save = PL.prepare "savepoint save" [||] in
let rollback = PL.prepare "rollback to save" [||] in
ignore (PL.execute_plan save [||]);
ignore (PL.execute "create table foo(x integer)");
ignore (PL.execute_plan rollback [||]);
()
$$ LANGUAGE plocamlu;

SELECT manual_subxact_prepared();

/* test the context stack trace for nested execution levels
 */
CREATE FUNCTION notice_innerfunc() RETURNS int AS $$
ignore (PL.execute "DO LANGUAGE plocamlu $x$ PL.notice \"inside DO\" $x$");
PL.Int 1
$$ LANGUAGE plocamlu;

CREATE FUNCTION notice_outerfunc() RETURNS int AS $$
ignore (PL.execute "SELECT notice_innerfunc()");
PL.Int 1
$$ LANGUAGE plocamlu;

SELECT notice_outerfunc();

/* test error logged with an underlying exception that includes a detail
 * string (bug #18070).
 */
CREATE FUNCTION ocaml_error_detail() RETURNS SETOF text AS $$
  let plan = PL.prepare "SELECT to_date('xy', 'DD') d" [||] in
  let cur = PL.cursor_plan plan [||] in
  let rec acc xs =
    let batch = PL.fetch cur 1 in
    if batch.nrows = 0 then List.rev xs
    else acc (List.assoc "d" batch.rows.(0) :: xs)
  in
  PL.Array (Array.of_list (acc []))
$$ LANGUAGE plocamlu;

SELECT ocaml_error_detail();
